Predictive Model Building
=========================

—–I am going to use different predictivve modeling techniques to find
the best model for this data (simple linear model then forward something
then KNN)

The data being analyzed regarding commercail rental properties from
across the Unites States contains twenty-one variables, ranging from the
rent amount charged to tenants to the annual precipitation of the
buildings’ geographoic region to whether or not the building is
economically-green certified. The full list of variables can be seen
below.

    ## Observations: 7,894
    ## Variables: 23
    ## $ CS_PropertyID     <int> 379105, 122151, 379839, 94614, 379285, 94765, 236...
    ## $ cluster           <int> 1, 1, 1, 1, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8...
    ## $ size              <int> 260300, 67861, 164848, 93372, 174307, 231633, 210...
    ## $ empl_gr           <dbl> 2.22, 2.22, 2.22, 2.22, 2.22, 2.22, 4.01, 4.01, 4...
    ## $ Rent              <dbl> 38.56, 28.57, 33.31, 35.00, 40.69, 43.16, 12.50, ...
    ## $ leasing_rate      <dbl> 91.39, 87.14, 88.94, 97.04, 96.58, 92.74, 94.33, ...
    ## $ stories           <int> 14, 5, 13, 13, 16, 14, 11, 15, 31, 21, 11, 15, 15...
    ## $ age               <int> 16, 27, 36, 46, 5, 20, 38, 24, 34, 36, 32, 25, 26...
    ## $ renovated         <int> 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0...
    ## $ class_a           <int> 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1...
    ## $ class_b           <int> 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0...
    ## $ LEED              <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
    ## $ Energystar        <int> 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1...
    ## $ green_rating      <int> 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1...
    ## $ net               <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0...
    ## $ amenities         <int> 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0...
    ## $ cd_total_07       <int> 4988, 4988, 4988, 4988, 4988, 4988, 2746, 2746, 2...
    ## $ hd_total07        <int> 58, 58, 58, 58, 58, 58, 1670, 1670, 1670, 1670, 1...
    ## $ total_dd_07       <int> 5046, 5046, 5046, 5046, 5046, 5046, 4416, 4416, 4...
    ## $ Precipitation     <dbl> 42.57, 42.57, 42.57, 42.57, 42.57, 42.57, 25.55, ...
    ## $ Gas_Costs         <dbl> 0.01370000, 0.01373149, 0.01373149, 0.01373149, 0...
    ## $ Electricity_Costs <dbl> 0.02900000, 0.02904455, 0.02904455, 0.02904455, 0...
    ## $ cluster_rent      <dbl> 36.78, 36.78, 36.78, 36.78, 36.78, 36.78, 17.50, ...

What is the best model for predicting price?
--------------------------------------------

A few different predictive models were run in order to determine which
model most accurately predicted the price of the buildings in our
dataset and can hopefully be used to predict prices of buildings our
dataset. Although the prices of the buildings is not a variable in the
data set, rent, gas costs, and electricity costs have been combined in
order to create a price variable for each building. Whether or not a
building is LEED certified and whether or not a building is Energystar
certified werre decided to keep seperately, as the two indicate two
different kinds of green certifications. The altered data can be seen
below.

    ## Observations: 7,894
    ## Variables: 21
    ## $ CS_PropertyID <int> 379105, 122151, 379839, 94614, 379285, 94765, 236739,...
    ## $ cluster       <int> 1, 1, 1, 1, 1, 1, 6, 6, 6, 6, 6, 6, 6, 6, 6, 6, 8, 8,...
    ## $ size          <int> 260300, 67861, 164848, 93372, 174307, 231633, 210038,...
    ## $ empl_gr       <dbl> 2.22, 2.22, 2.22, 2.22, 2.22, 2.22, 4.01, 4.01, 4.01,...
    ## $ leasing_rate  <dbl> 91.39, 87.14, 88.94, 97.04, 96.58, 92.74, 94.33, 91.0...
    ## $ stories       <int> 14, 5, 13, 13, 16, 14, 11, 15, 31, 21, 11, 15, 15, 31...
    ## $ age           <int> 16, 27, 36, 46, 5, 20, 38, 24, 34, 36, 32, 25, 26, 28...
    ## $ renovated     <int> 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,...
    ## $ class_a       <int> 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0,...
    ## $ class_b       <int> 0, 1, 1, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,...
    ## $ LEED          <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
    ## $ Energystar    <int> 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,...
    ## $ green_rating  <int> 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,...
    ## $ net           <int> 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,...
    ## $ amenities     <int> 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0,...
    ## $ cd_total_07   <int> 4988, 4988, 4988, 4988, 4988, 4988, 2746, 2746, 2746,...
    ## $ hd_total07    <int> 58, 58, 58, 58, 58, 58, 1670, 1670, 1670, 1670, 1670,...
    ## $ total_dd_07   <int> 5046, 5046, 5046, 5046, 5046, 5046, 4416, 4416, 4416,...
    ## $ Precipitation <dbl> 42.57, 42.57, 42.57, 42.57, 42.57, 42.57, 25.55, 25.5...
    ## $ cluster_rent  <dbl> 36.78, 36.78, 36.78, 36.78, 36.78, 36.78, 17.50, 17.5...
    ## $ Price         <dbl> 38.60270, 28.61278, 33.35278, 35.04278, 40.73278, 43....

The first model used to predict building prices was a simple linear
model. The data was split into two different sets, the training set that
contained 80% of the buildings observations, and the testing set that
contained the remaining 20% of observations. The training set was used
to create a multiple linear regression model using variables that were
presumed to have a significant affect on price.

    ## 
    ## Call:
    ## lm(formula = Price ~ age + renovated + LEED + Energystar + class_a + 
    ##     cluster, data = greenb_train)
    ## 
    ## Residuals:
    ##     Min      1Q  Median      3Q     Max 
    ## -29.106  -8.599  -2.452   5.136 219.362 
    ## 
    ## Coefficients:
    ##               Estimate Std. Error t value Pr(>|t|)    
    ## (Intercept) 21.0734900  0.5467180  38.545  < 2e-16 ***
    ## age          0.0321140  0.0072055   4.457 8.46e-06 ***
    ## renovated   -2.9650378  0.4167665  -7.114 1.25e-12 ***
    ## LEED         0.8632107  2.1059278   0.410   0.6819    
    ## Energystar  -1.4142421  0.6689987  -2.114   0.0346 *  
    ## class_a      7.5879280  0.4305266  17.625  < 2e-16 ***
    ## cluster      0.0069404  0.0004495  15.440  < 2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## 
    ## Residual standard error: 14.19 on 6308 degrees of freedom
    ## Multiple R-squared:  0.09311,    Adjusted R-squared:  0.09225 
    ## F-statistic: 107.9 on 6 and 6308 DF,  p-value: < 2.2e-16

    ## The price-predicting function found from this model is:

Here is a sumary of the result. The formula is Price = 21.07 +
0.03*(age) + -2.97* (renovated) + 0.86*(LEED) + -1.41*(Energystar) +
7.59*(class\_a) + 0.01*(cluster). Thisodfned

    ## The price-predicting function found from this model is:
